//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMessenger.Client.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMessenger.Client.Resources.Strings.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автозавантаження з використанням даних.
        /// </summary>
        internal static string Autodownload_Using_Data {
            get {
                return ResourceManager.GetString("Autodownload_Using_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увімкніть, щоб дозволити завантажувати через мобільні дані, якщо Wi-Fi недоступний.
        /// </summary>
        internal static string Autodownload_Using_Data_Subtitle {
            get {
                return ResourceManager.GetString("Autodownload_Using_Data_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темна тема.
        /// </summary>
        internal static string Dark_Mode {
            get {
                return ResourceManager.GetString("Dark_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування завантажень.
        /// </summary>
        internal static string Download_Settings {
            get {
                return ResourceManager.GetString("Download_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групи.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Англійська.
        /// </summary>
        internal static string Lang_En {
            get {
                return ResourceManager.GetString("Lang_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Українська.
        /// </summary>
        internal static string Lang_Uk {
            get {
                return ResourceManager.GetString("Lang_Uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Світла тема.
        /// </summary>
        internal static string Light_Mode {
            get {
                return ResourceManager.GetString("Light_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Діалоги.
        /// </summary>
        internal static string Messenger {
            get {
                return ResourceManager.GetString("Messenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новини.
        /// </summary>
        internal static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тільки Wi-Fi.
        /// </summary>
        internal static string Only_Wifi {
            get {
                return ResourceManager.GetString("Only_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профіль.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути всі пошуки.
        /// </summary>
        internal static string See_All_Searches {
            get {
                return ResourceManager.GetString("See_All_Searches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть мову.
        /// </summary>
        internal static string Select_Lang {
            get {
                return ResourceManager.GetString("Select_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть тему.
        /// </summary>
        internal static string Select_Theme {
            get {
                return ResourceManager.GetString("Select_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Торкніться, щоб шукати текст.
        /// </summary>
        internal static string Semantic_Description_Tap_Search {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Натисніть, щоб переглянути всі категорії.
        /// </summary>
        internal static string Semantic_Description_Tap_See_All_Categories {
            get {
                return ResourceManager.GetString("Semantic_Description_Tap_See_All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увімкніть або вимкніть темний режим.
        /// </summary>
        internal static string Semantic_Description_Toggle_Mode {
            get {
                return ResourceManager.GetString("Semantic_Description_Toggle_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увімкніть або вимкніть налаштування Wi-Fi.
        /// </summary>
        internal static string Semantic_Description_Toggle_Wifi {
            get {
                return ResourceManager.GetString("Semantic_Description_Toggle_Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо-програма XMessenger розроблена в MAUI.
        /// </summary>
        internal static string Settings_Info {
            get {
                return ResourceManager.GetString("Settings_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Як в системі.
        /// </summary>
        internal static string Theme_Follow_System {
            get {
                return ResourceManager.GetString("Theme_Follow_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоро буде🤗.
        /// </summary>
        internal static string To_Be_Soon {
            get {
                return ResourceManager.GetString("To_Be_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.1.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
